### ISSUE TITLE
Fit to screen in Safari doesn't fit to screen (and is not even same width)

### ISSUE THREAD

**Issue by bestchai** [RepoGrams/RepoGrams#51]
![fit-to-screen-safari](https://cloud.githubusercontent.com/assets/353346/4947593/9cb3c1f8-6626-11e4-92cb-d739c50298de.png)

**Comment by Suizidhamster** [comment]
I somehow ignored the fact that floating-point arithmetic will always result in a minor rounding error, per definition.
Even if I use integer values all the time, I'll have to divide my results by 100 to get the percentage in the end, which results in a minor rounding error, again.
However, I tried to minimize the effect and uploaded my changes, 4a2afffc0ccf25895c7ce1e34a27fd08eab3a863.

**Comment by daniboy** [comment]
I haven't had the time to test this today. I will test this tomorrow morning (my timezone)

**Comment by daniboy** [comment]
I'm actually getting slightly worse results with this branch:

branch master:
![master](https://cloud.githubusercontent.com/assets/1839738/6026739/0ba7824c-ab92-11e4-956e-f588688a78e0.png)

branch issue#51:
![issue#51](https://cloud.githubusercontent.com/assets/1839738/6026747/1561676c-ab92-11e4-9841-bdbce2548f98.png)

**Comment by daniboy** [comment]
I'm lowering the priority for this one since it looks relatively fine on Chrome and Firefox. For the user study we can ask the participants to choose one of these two browsers.

**Comment by daniboy** [comment]
I learned today about `display: flex`, which seems like it *might* help solve this issue by moving this calculation from JavaScript to the CSS layout engine (which might or might not use doubles instead of floats)

It's probably not worth investing a lot of effort on fixing this before the user study, but it's good to keep this in mind.

http://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by daniboy** [comment]
Replaced by #95.
