### ISSUE TITLE
Trying to add a non-git repo URL shows blank error message

### ISSUE THREAD

**Issue by bestchai** [RepoGrams/RepoGrams#85]
Adding http://www.google.com shows a blank error msg (red box that is empty).

**Comment by daniboy** [comment]
@bestchai does this still happen? I think I accidentally fixed it

**Comment by bestchai** [comment]
I'm currently not getting any error msg -- for http://www.google.com and https://www.google.com
It just tries to use them and then nothing happens.

**Comment by daniboy** [comment]
Look like a missing `/` after the domain name causes a segfault in the C library that pygit2 uses (libgit2) which actually caused the Python application to close, but the docker image just restarted it. Still, pretty bad stuff!

It was fixed in a later version, so I updated the docker image to use that, hopefully this should be fixed now.
