### ISSUE TITLE
Same author has multiple colors

### ISSUE THREAD

**Issue by whitecat** [RepoGrams/RepoGrams#87]
Check out this project: 
https://github.com/CPSC310-2014W2/Chitoge.git

Use the metric: "Commit Author"
Also recommend using Browse Length: "Fixed"
The same author has 3 colors. 
hugolee: Pink, Green
Hugo: Red

Hugo and hugolee are the same people.

**Comment by daniboy** [comment]
This turns out to be a bigger problem than we initially thought. We use the email address to assign a colour to each author. Authors often use different email addresses (e.g., jane.doe@some-institution.com and jane.doe@gmail.com, depending on where Jane is committing her code from). Even if we connected to GitHub and tried to poll a unique person ID, they don't always notify GitHub that both email addresses belong to the same account.

I doubt that a technological solution is the right one here, this is a perfect spot for the front-end customizable metrics that we discussed but never documented. I'll open an issue for that are reference to it.

**Comment by daniboy** [comment]
Depends on issue #90.

Once customizable metrics exist, we would modify this metrics as follows:
1. The server-side code will send the commit author name + email instead of a computer number based on commit author email
2. The client-side code will match one name per value by default
3. The customization will display all names and their matched colour in this form: "[COLOR] Jane Doe <jane.doe.1@example.com>, Jane Doe <jane.doe.2@example.com>". The names will be drag-and-droppable between the different groupings, with a "new group" at the bottom to un-match names in case two different people have the same name:
![screenshot from 2015-04-15 13 15 55](https://cloud.githubusercontent.com/assets/1839738/7168345/912a1ea4-e371-11e4-8e80-d48e0c1aa049.png)

**Comment by daniboy** [comment]
@whitecat I made some changes so that, based on exact string match for author name, they would receive the same colour. Test it on the staging server and let me know if it works for you: http://repograms.net:8888/

@bestchai this change makes it so that now the colours assigned to authors ARE comparable between the projects (e.g., if you committed to Repo1 and Repo2, you will have the same colour in both) - the biggest part of this change is that we're closing on solving #90 (the `Mapper` class pretty much supports it now, and we need to solve it in the front end).

**Comment by daniboy** [comment]
@whitecat, @bestchai I moved the implementation to the backend again and deployed to the staging server: http://repograms.net:8888/
Let me know if it works for you, in which case I'll merge to master and close this issue and issue #92.

**Comment by whitecat** [comment]
Works for me.

**Comment by bestchai** [comment]
Daniel, go ahead and merge.

iv.
