### ISSUE TITLE
Come up with descriptive text and icons for block lengths dialog

### ISSUE THREAD

**Issue by bestchai** [RepoGrams/RepoGrams#99]
Text for block lengths and normalization modes.

Choose icons from here:
http://fortawesome.github.io/Font-Awesome/icons/

**Comment by daniboy** [comment]
(From @bestchai's email)

 Here is text you can use for the block length/normalization pop-up --

All normalized:
-------------------------
Short text: Globally normalized
Description: Commit block width is normalized across projects and is
therefore comparable between projects.

Individually normalized:
---------------------------------
Short text: Project normalized
Description: Commit block widths are incomparable between projects but
are comparable within the same project. Widths are selected so that
each project fills the screen.
Icon: http://fortawesome.github.io/Font-Awesome/icon/align-justify/

Linear description: Block width is scaled linearly according to LOC changed.

Logarithmic description: Block width is scaled logarithmically
according to LOC changed.

For linear/logarithmic I was looking all over for a line icons that
run linearly/logarithmically from bottom left to top right. I found
some linear examples, but we'll need to draw a logarithmic one.. for
now, I think that we may want to drop the icons on these (since
consistency is important, and not having icons on all three looks
strange). We can try to remedy this later (can create an issue for
this).

**Comment by daniboy** [comment]
I created custom icons for the three modes, we can use these for now and if you want to change them we can do it later.

**Comment by bestchai** [comment]
These look great. A minor change to the icons that I would suggest is to decrease the number of tic marks, or to make the tics smaller/less prominent.

**Comment by daniboy** [comment]
I created a new repository to house the raw versions of the icons (I don't want to contaminate this repository with raw graphic files) and added a README file there. Feel free to play around with that repository :)
https://github.com/RepoGrams/RepoGrams-Custom-icons
